apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-service
  template:
    metadata:
      labels:
        app: go-web-service
    spec:
      containers:
      - name: go-web-service
        image: go-web-service:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  type: NodePort
  selector:
    app: go-web-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
